# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Hash-Interpolate
version:      0.05
version_from: Interpolate.pm
installdirs:  site
requires:
    Scalar::Util:                  1.1
    Test::More:                    0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
