---
name: Tie-Hash-Interpolate
version: 0.06
author:
  - 'Dan Boorstein <danboo@cpan.org>'
abstract: tied mathematical interpolation/extrapolation
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Tie::Hash::Interpolate:
    file: lib/Tie/Hash/Interpolate.pm
    version: 0.06
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
